### ISSUE TITLE
还继续维护吗

### ISSUE THREAD

**Issue by TahmLi** [mimicode/tksdk#2]
https://open.pinduoduo.com/application/document/api?id=pdd.ddk.order.list.range.get用时间段查询推广订单接口
希望使用这个接口，但是在pddopensdk里目前还没找到

**Comment by mimicode** [comment]
维护，可能我这边没用到。你可以提一个request 或者等我这边增加这个

**Comment by mimicode** [comment]
已经增加了
https://github.com/mimicode/tksdk/commit/9bf7461c2509ddc98ebd75305e7473727a398126
