### ISSUE TITLE
jd.union.open.promotion.common.get

### ISSUE THREAD

**Issue by TahmLi** [mimicode/tksdk#3]
调用JdUnionOpenPromotionCommonGetRequest方法，返回{"error_response":{"code":"67","en_desc":"platform connecting service process unknown exception information(Solution reference: https://jos.jd.com/commondoc?listId=171)","zh_desc":"java.lang.NumberFormatException: For input string: \"\"（解决方案参考: https://jos.jd.com/commondoc?listId=171）"}}
经过查找京东文档code67是平台连接后端服务处理过程中出现未知异常信息，你有遇到过吗

**Comment by mimicode** [comment]
应该是入参导致的 对方服务无法解析 报错了 
看这里 
[:"java.lang.NumberFormatException]  For input string: ""

**Comment by TahmLi** [comment]
感谢~
